package com.example.creditcardtracker.theme

import androidx.compose.ui.graphics.Color

// Light Theme Tokens from Tonal Logic YAML Spec
val md_theme_light_primary = Color(0xFF4F378A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6750A4)
val md_theme_light_onPrimaryContainer = Color(0xFFE0D2FF)
val md_theme_light_secondary = Color(0xFF625B71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DEF9)
val md_theme_light_onSecondaryContainer = Color(0xFF686177)
val md_theme_light_tertiary = Color(0xFF633B48)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF7D5260)
val md_theme_light_onTertiaryContainer = Color(0xFFFFCBDA)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFFDF8FD)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFDF8FD)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE5E1E7)
val md_theme_light_onSurfaceVariant = Color(0xFF494551)
val md_theme_light_outline = Color(0xFF7A7582)
val md_theme_light_outlineVariant = Color(0xFFCBC4D2)
val md_theme_light_surfaceTint = Color(0xFF6750A4)
val md_theme_light_inverseSurface = Color(0xFF313034)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF5)
val md_theme_light_inversePrimary = Color(0xFFCFBCFF)
val md_theme_light_surfaceDim = Color(0xFFDDD9DE)
val md_theme_light_surfaceBright = Color(0xFFFDF8FD)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF7F2F8)
val md_theme_light_surfaceContainer = Color(0xFFF1ECF2)
val md_theme_light_surfaceContainerHigh = Color(0xFFEBE7EC)
val md_theme_light_surfaceContainerHighest = Color(0xFFE5E1E7)

// Dark Theme Tokens (Matching Luminous Abyss spec)
val md_theme_dark_primary = Color(0xFF4CD6FB)
val md_theme_dark_onPrimary = Color(0xFF003642)
val md_theme_dark_primaryContainer = Color(0xFF00B4D8)
val md_theme_dark_onPrimaryContainer = Color(0xFF00414F)
val md_theme_dark_secondary = Color(0xFF7DFFA2)
val md_theme_dark_onSecondary = Color(0xFF003918)
val md_theme_dark_secondaryContainer = Color(0xFF05E777)
val md_theme_dark_onSecondaryContainer = Color(0xFF00622E)
val md_theme_dark_tertiary = Color(0xFFFFBA27)
val md_theme_dark_onTertiary = Color(0xFF422C00)
val md_theme_dark_tertiaryContainer = Color(0xFFD79A00)
val md_theme_dark_onTertiaryContainer = Color(0xFF4F3600)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0B1326)
val md_theme_dark_onBackground = Color(0xFFDAE2FC)
val md_theme_dark_surface = Color(0xFF0B1326)
val md_theme_dark_onSurface = Color(0xFFDAE2FC)
val md_theme_dark_surfaceVariant = Color(0xFF2D3449)
val md_theme_dark_onSurfaceVariant = Color(0xFFBCC9CE)
val md_theme_dark_outline = Color(0xFF869398)
val md_theme_dark_outlineVariant = Color(0xFF3D494D)
val md_theme_dark_surfaceTint = Color(0xFF4CD6FB)
val md_theme_dark_inverseSurface = Color(0xFFDAE2FC)
val md_theme_dark_inverseOnSurface = Color(0xFF283044)
val md_theme_dark_inversePrimary = Color(0xFF00677D)
val md_theme_dark_surfaceDim = Color(0xFF0B1326)
val md_theme_dark_surfaceBright = Color(0xFF31394D)
val md_theme_dark_surfaceContainerLowest = Color(0xFF060E20)
val md_theme_dark_surfaceContainerLow = Color(0xFF131B2E)
val md_theme_dark_surfaceContainer = Color(0xFF171F32)
val md_theme_dark_surfaceContainerHigh = Color(0xFF222A3D)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2D3449)

